const APP_VERSION='V2';
const state={mode:'single',characterImages:[]};
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
$('#versionBadge').textContent=APP_VERSION; $('#footerVersion').textContent=APP_VERSION;
$$('.tab').forEach(b=>b.addEventListener('click',()=>{$$('.tab').forEach(x=>x.classList.toggle('active',x===b));$$('.panel').forEach(p=>p.classList.toggle('active',p.id===b.dataset.target));window.scrollTo({top:0,behavior:'smooth'});}));
$$('.choice').forEach(b=>b.addEventListener('click',()=>{state.mode=b.dataset.mode;$$('.choice').forEach(x=>x.classList.toggle('active',x===b));}));
function renderThumbs(images){$('#thumbs').innerHTML='';images.forEach(src=>{const img=document.createElement('img');img.src=src;img.alt='캐릭터 기준 이미지';$('#thumbs').append(img);});}
function fileToDataURL(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file);});}
$('#characterInput').addEventListener('change',async e=>{const files=[...e.target.files].slice(0,5);state.characterImages=await Promise.all(files.map(fileToDataURL));renderThumbs(state.characterImages);$('#saveStatus').classList.add('hidden');});
$('#saveCharacter').addEventListener('click',()=>{const name=$('#characterName').value.trim()||'MY CHARACTER';if(!state.characterImages.length){alert('기준 이미지를 먼저 추가해주세요.');return;}try{localStorage.setItem('dayframe.characterName',name);localStorage.setItem('dayframe.characterImages',JSON.stringify(state.characterImages));localStorage.setItem('dayframe.characterSavedAt',new Date().toISOString());$('#dnaText').textContent=`${name}의 기준 이미지 ${state.characterImages.length}장이 이 기기에 저장되었습니다. 실제 Character DNA 자동 분석은 이미지 분석 모델 연결 후 추가됩니다.`;$('#saveStatusText').textContent=`${name} · 기준 이미지 ${state.characterImages.length}장 · 이 기기에 저장됨`;$('#saveStatus').classList.remove('hidden');const btn=$('#saveCharacter');btn.textContent='✓ 저장됨';setTimeout(()=>btn.textContent='캐릭터 다시 저장',1400);}catch(err){alert('이미지 용량이 커서 저장하지 못했습니다. 이미지 수나 용량을 줄여 다시 시도해주세요.');}});
$('#makeHighlight').addEventListener('click',()=>{const t=$('#diaryText').value.trim();if(!t){alert('오늘의 기록을 먼저 적어주세요.');return;}const sentences=t.split(/(?<=[.!?。]|다\.)\s+|\n+/).map(x=>x.trim()).filter(Boolean);const n=state.mode==='four'?4:1;$('#highlightText').textContent=sentences.slice(0,n).join(state.mode==='four'?'  ·  ':' ');$('#highlightCard').classList.remove('hidden');localStorage.setItem('dayframe.diary',t);});
const caption=$('#previewCaption');$('#captionInput').addEventListener('input',e=>caption.textContent=e.target.value);$('#fontSize').addEventListener('input',e=>caption.style.fontSize=e.target.value+'px');$('#letterSpacing').addEventListener('input',e=>caption.style.letterSpacing=e.target.value+'px');$('#lineHeight').addEventListener('input',e=>caption.style.lineHeight=e.target.value);
$('#generateScene').addEventListener('click',()=>alert('V2에서는 캐릭터 기준 이미지의 로컬 저장과 복원을 지원합니다. 실제 Character DNA 분석과 이미지 생성 API는 다음 연결 단계에서 추가합니다.'));
$('#resetDraft').addEventListener('click',()=>{if(confirm('현재 작성 중인 기록과 조절값을 초기화할까요?')){localStorage.removeItem('dayframe.diary');location.reload();}});
window.addEventListener('DOMContentLoaded',()=>{const name=localStorage.getItem('dayframe.characterName');const diary=localStorage.getItem('dayframe.diary');let images=[];try{images=JSON.parse(localStorage.getItem('dayframe.characterImages')||'[]');}catch{}if(name)$('#characterName').value=name;if(diary)$('#diaryText').value=diary;if(images.length){state.characterImages=images;renderThumbs(images);$('#dnaText').textContent=`${name||'MY CHARACTER'}의 기준 이미지 ${images.length}장이 저장되어 있습니다.`;$('#saveStatusText').textContent=`${name||'MY CHARACTER'} · 기준 이미지 ${images.length}장 · 저장된 캐릭터 불러옴`;$('#saveStatus').classList.remove('hidden');}});
if('serviceWorker' in navigator){window.addEventListener('load',async()=>{try{const reg=await navigator.serviceWorker.register('./sw.js');reg.update();reg.addEventListener('updatefound',()=>{const worker=reg.installing;worker?.addEventListener('statechange',()=>{if(worker.state==='installed'&&navigator.serviceWorker.controller)$('#updateToast').classList.remove('hidden');});});navigator.serviceWorker.addEventListener('controllerchange',()=>location.reload());}catch(e){console.warn('Service worker registration failed',e);}});}
$('#refreshApp').addEventListener('click',()=>{navigator.serviceWorker.getRegistration().then(reg=>reg?.waiting?.postMessage({type:'SKIP_WAITING'}));});