const APP_VERSION='V1';
const state={mode:'single'};
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
$('#versionBadge').textContent=APP_VERSION; $('#footerVersion').textContent=APP_VERSION;
$$('.tab').forEach(b=>b.addEventListener('click',()=>{ $$('.tab').forEach(x=>x.classList.toggle('active',x===b)); $$('.panel').forEach(p=>p.classList.toggle('active',p.id===b.dataset.target)); window.scrollTo({top:0,behavior:'smooth'}); }));
$$('.choice').forEach(b=>b.addEventListener('click',()=>{state.mode=b.dataset.mode;$$('.choice').forEach(x=>x.classList.toggle('active',x===b));}));
$('#characterInput').addEventListener('change',e=>{const files=[...e.target.files].slice(0,5);$('#thumbs').innerHTML='';files.forEach(file=>{const img=document.createElement('img');img.src=URL.createObjectURL(file);img.alt='캐릭터 기준 이미지';$('#thumbs').append(img);});});
$('#saveCharacter').addEventListener('click',()=>{const name=$('#characterName').value.trim()||'MY CHARACTER';localStorage.setItem('dayframe.characterName',name);$('#dnaText').textContent=`${name}의 Character DNA 저장 준비가 되었습니다. 실제 이미지 특징 분석 모델 연결 전까지 기준 이미지를 캐릭터 정체성의 최우선 참조로 사용하도록 설계됩니다.`;});
$('#makeHighlight').addEventListener('click',()=>{const t=$('#diaryText').value.trim();if(!t){alert('오늘의 기록을 먼저 적어주세요.');return;}const sentences=t.split(/(?<=[.!?。]|다\.)\s+|\n+/).map(x=>x.trim()).filter(Boolean);const n=state.mode==='four'?4:1;const picked=sentences.slice(0,n);$('#highlightText').textContent=picked.join(state.mode==='four'?'  ·  ':' ');$('#highlightCard').classList.remove('hidden');localStorage.setItem('dayframe.diary',t);});
const caption=$('#previewCaption');$('#captionInput').addEventListener('input',e=>caption.textContent=e.target.value);$('#fontSize').addEventListener('input',e=>caption.style.fontSize=e.target.value+'px');$('#letterSpacing').addEventListener('input',e=>caption.style.letterSpacing=e.target.value+'px');$('#lineHeight').addEventListener('input',e=>caption.style.lineHeight=e.target.value);
$('#generateScene').addEventListener('click',()=>alert('V1은 앱 구조와 캐릭터 일관성 파이프라인의 기반 버전입니다. 다음 단계에서 실제 Character DNA 분석과 이미지 생성 API를 연결합니다.'));
$('#resetDraft').addEventListener('click',()=>{if(confirm('현재 작성 중인 기록과 조절값을 초기화할까요?')){localStorage.removeItem('dayframe.diary');location.reload();}});
window.addEventListener('DOMContentLoaded',()=>{const name=localStorage.getItem('dayframe.characterName');const diary=localStorage.getItem('dayframe.diary');if(name)$('#characterName').value=name;if(diary)$('#diaryText').value=diary;});
if('serviceWorker' in navigator){window.addEventListener('load',async()=>{try{const reg=await navigator.serviceWorker.register('./sw.js');reg.update();reg.addEventListener('updatefound',()=>{const worker=reg.installing;worker?.addEventListener('statechange',()=>{if(worker.state==='installed'&&navigator.serviceWorker.controller)$('#updateToast').classList.remove('hidden');});});navigator.serviceWorker.addEventListener('controllerchange',()=>location.reload());}catch(e){console.warn('Service worker registration failed',e);}});}
$('#refreshApp').addEventListener('click',()=>{navigator.serviceWorker.getRegistration().then(reg=>reg?.waiting?.postMessage({type:'SKIP_WAITING'}));});
