(()=>{const PATCH_VERSION='V21';$('#versionBadge').textContent=PATCH_VERSION;$('#footerVersion').textContent=PATCH_VERSION;
const styleKeys=['font','size','spacing','line','color','align','valign','box','boxColor','boxOpacity','borderColor','padding','border','lineTexture'];
let syncFour=true;
function ensureTextDefaults(t){if(!t)return;t.boxOpacity=t.boxOpacity??1;t.lineTexture=t.lineTexture??0.28;t.valign=t.valign||'middle';}
function copyMasterStyle(){if(S.mode!=='four'||!syncFour||!S.texts.length)return;const master=S.texts[0];ensureTextDefaults(master);S.texts.slice(1).forEach(t=>{ensureTextDefaults(t);styleKeys.forEach(k=>t[k]=master[k]);});}
function refreshMasterUI(){const card=document.querySelector('.editor-controls .editor-card');if(!card)return;if(document.querySelector('#fourStyleSync'))return;const wrap=document.createElement('div');wrap.className='style-sync-card';wrap.innerHTML=`<div class="style-sync-copy"><div><strong>4컷 텍스트 스타일 통일</strong><small>1컷 스타일을 2–4컷에 자동 적용 · 문구와 위치는 컷별 유지</small></div><button type="button" id="fourStyleSync" class="sync-toggle active" aria-pressed="true">ON</button></div><button type="button" id="applyMasterStyle" class="secondary compact-secondary">1컷 스타일 지금 전체 적용</button>`;card.insertAdjacentElement('afterend',wrap);$('#fourStyleSync').onclick=()=>{syncFour=!syncFour;$('#fourStyleSync').classList.toggle('active',syncFour);$('#fourStyleSync').textContent=syncFour?'ON':'OFF';$('#fourStyleSync').setAttribute('aria-pressed',String(syncFour));if(syncFour){copyMasterStyle();controls();draw();}};$('#applyMasterStyle').onclick=()=>{copyMasterStyle();draw();};}
function addBoxControls(){const borderWidth=$('#borderWidth');if(!borderWidth||$('#boxOpacity'))return;const opacity=document.createElement('label');opacity.className='range-label';opacity.innerHTML='박스 투명도 <input id="boxOpacity" type="range" min="0" max="100" value="100"/>';borderWidth.parentElement.append(opacity);const texture=document.createElement('label');texture.className='range-label';texture.innerHTML='라인 질감 <input id="lineTexture" type="range" min="0" max="100" value="28"/>';borderWidth.parentElement.append(texture);$('#boxOpacity').oninput=e=>{const t=S.texts[S.active];if(!t)return;t.boxOpacity=+e.target.value/100;if(S.active===0)copyMasterStyle();draw();};$('#lineTexture').oninput=e=>{const t=S.texts[S.active];if(!t)return;t.lineTexture=+e.target.value/100;if(S.active===0)copyMasterStyle();draw();};}
const oldControls=controls;controls=function(){const t=S.texts[S.active];ensureTextDefaults(t);oldControls();if(t){if($('#boxOpacity'))$('#boxOpacity').value=Math.round(t.boxOpacity*100);if($('#lineTexture'))$('#lineTexture').value=Math.round(t.lineTexture*100);}if($('#fourStyleSync'))$('#fourStyleSync').closest('.style-sync-card').classList.toggle('hidden',S.mode!=='four');};
function rgba(hex,a){const h=hex.replace('#','');const v=parseInt(h.length===3?h.split('').map(x=>x+x).join(''):h,16);return `rgba(${(v>>16)&255},${(v>>8)&255},${v&255},${a})`;}
function traceBoxPath(t,x,y,w,h,cx){if(t.box==='bubble')speechPath(x,y,w,h,Math.min(32,h*.35),cx);else{X.beginPath();X.rect(x,y,w,h);}}
function roughenStraightEdges(t,x,y,w,h){const strength=Math.max(0,Math.min(1,t.lineTexture??0));if(!strength)return;X.save();X.fillStyle=rgba(t.borderColor,0.16+strength*.2);const count=Math.round((w+h)*0.055*strength);for(let i=0;i<count;i++){const side=i%4;let px,py;if(side===0){px=x+Math.random()*w;py=y+(Math.random()-.5)*2.4}else if(side===1){px=x+w+(Math.random()-.5)*2.4;py=y+Math.random()*h}else if(side===2){px=x+Math.random()*w;py=y+h+(Math.random()-.5)*2.4}else{px=x+(Math.random()-.5)*2.4;py=y+Math.random()*h}const r=.45+Math.random()*1.15*strength;X.beginPath();X.arc(px,py,r,0,Math.PI*2);X.fill();}X.restore();}
function measuredLines(t,L){X.font=`${t.size}px ${t.font}`;return L.ls.map((ln,i)=>{const m=X.measureText(ln||' ');const ascent=m.actualBoundingBoxAscent||t.size*.72,descent=m.actualBoundingBoxDescent||t.size*.2;return{ln,width:L.ws[i],ascent,descent};});}
drawText=function(t){if(!t?.text)return;ensureTextDefaults(t);let L=layout(t,C.width*(S.mode==='four'?.34:.76)),cx=C.width*t.x/100,cy=C.height*t.y/100,p=t.padding,metrics=measuredLines(t,L);const visualLineH=t.size*t.line;const glyphBlockH=metrics.length===1?metrics[0].ascent+metrics[0].descent:(metrics.length-1)*visualLineH+metrics[0].ascent+metrics.at(-1).descent;let w=L.w+2*p,h=glyphBlockH+2*p,x=cx-w/2,y=cy-h/2;if(t.box!=='plain'){traceBoxPath(t,x,y,w,h,cx);X.fillStyle=rgba(t.boxColor,t.boxOpacity);X.fill();X.strokeStyle=t.borderColor;X.lineWidth=t.border;X.lineJoin='round';X.stroke();roughenStraightEdges(t,x,y,w,h);}X.font=`${t.size}px ${t.font}`;X.fillStyle=t.color;X.textBaseline='alphabetic';let contentTop=t.box==='plain'?cy-glyphBlockH/2:t.valign==='top'?y+p:t.valign==='bottom'?y+h-p-glyphBlockH:y+(h-glyphBlockH)/2;metrics.forEach((m,i)=>{let total=m.width,start=t.align==='center'?cx-total/2:t.align==='right'?cx+L.w/2-total:cx-L.w/2;const baseline=contentTop+m.ascent+i*visualLineH;[...m.ln].forEach(ch=>{X.fillText(ch,start,baseline);start+=X.measureText(ch).width+t.spacing;});});};
function installStyleSyncListeners(){['fontFamily','fontColor','fontSize','letterSpacing','lineHeight','boxColor','borderColor','boxPadding','borderWidth'].forEach(id=>{const el=$('#'+id);if(el)el.addEventListener('input',()=>{if(S.active===0){copyMasterStyle();draw();}},false);});$$('.bubble-style,.align,.valign').forEach(el=>el.addEventListener('click',()=>{setTimeout(()=>{if(S.active===0){copyMasterStyle();draw();}},0);},false));}
const oldSync=sync;sync=function(){oldSync();S.texts.forEach(ensureTextDefaults);copyMasterStyle();controls();draw();};
window.addEventListener('DOMContentLoaded',()=>{refreshMasterUI();addBoxControls();installStyleSyncListeners();});
if(document.readyState!=='loading'){refreshMasterUI();addBoxControls();installStyleSyncListeners();}
if('serviceWorker'in navigator){navigator.serviceWorker.register('./sw.js?v=21').catch(()=>{});}
})();